/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD_Char_1.h"
#include "MOTOR_2_DIR.h"
#include "MOTOR_2_DIR_aliases.h"
#include "MOTOR_1_DIR.h"
#include "MOTOR_1_DIR_aliases.h"
#include "MOTOR_1_STEP.h"
#include "MOTOR_1_STEP_aliases.h"
#include "MOTOR_1_EN.h"
#include "MOTOR_1_EN_aliases.h"
#include "MOTOR_2_STEP.h"
#include "MOTOR_2_STEP_aliases.h"
#include "MOTOR_2_EN.h"
#include "MOTOR_2_EN_aliases.h"
#include "LCD_E.h"
#include "LCD_E_aliases.h"
#include "LCD_RS.h"
#include "LCD_RS_aliases.h"
#include "LCD_D4.h"
#include "LCD_D4_aliases.h"
#include "LCD_D5.h"
#include "LCD_D5_aliases.h"
#include "LCD_D7.h"
#include "LCD_D7_aliases.h"
#include "LCD_D6.h"
#include "LCD_D6_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

